server:
  port: 11000

embedding:
  api:
    url: http://localhost:12000

spring:
  application:
    name: spring-vectordb

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

feign:
  client:
    config:
      default:
        connectTimeOut: 6000000
        readTimeout: 6000000

